global:
  resolve_timeout: 5m

templates:
  - /etc/prometheus/templates/*.tmpl

route:
  receiver: alert-telegram
  group_by: ["alertname", "instance", "severity"]
  group_wait: 30s
  group_interval: 10s
  repeat_interval: 30s
  routes:
    - match:
        alertname: telegram
      receiver: alert-telegram

receivers:
  - name: "alert-telegram"
    telegram_configs:
      - bot_token: xxx:xxx
        api_url: https://api.telegram.org
        chat_id: -xxx
        parse_mode: ""
