auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /data/loki
  storage:
    filesystem:
      chunks_directory: /data/loki/chunks
      rules_directory: /data/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-08-20
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

compactor:
  retention_enabled: true
  # working_directory is the directory where marked chunks and temporary tables will be saved.
  working_directory: /data/loki/retention
  compaction_interval: 10m
  # retention_delete_delay is the delay after which the Compactor will delete marked chunks.
  retention_delete_delay: 2h
  # retention_delete_worker_count specifies the maximum quantity of goroutine workers instantiated to delete chunks
  retention_delete_worker_count: 150
  delete_request_store: filesystem

limits_config:
  #retention_period: 90d
  retention_period: ${LOKI_RETENTION_PERIOD:-90d}
# will be enable alert manager later
# ruler:
#   alertmanager_url: http://localhost:9093
