apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
  - name: Loki
  - name: Alertmanager

# list of datasources to insert/update depending
# whats available in the database
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://localhost:9090
    #basicAuth: false
    isDefault: true
    version: 1
    editable: false
    jsonData:
      timeInterval: "30s"
      prometheusVersion: 2.45.0
      manageAlerts: true
      alertmanagerUid: alertmanager
      prometheusType: Prometheus #Cortex | Mimir | Prometheus | Thanos
    httpMethod: POST
    cacheLevel: 'High'
    incrementalQuerying: true
    incrementalQueryOverlapWindow: 10m
  - name: Loki
    type: loki
    uid: loki
    url: http://localhost:3100
    jsonData:
      derivedFields:
        - name: 'trace_id'
          matcherType: 'label'
          matcherRegex: 'trace_id'
          url: '$${__value.raw}'
          datasourceUid: 'tempo'
          urlDisplayLabel: 'Trace: $${__value.raw}'
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://localhost:3200
    jsonData:
      tracesToLogsV2:
        customQuery: true
        datasourceUid: 'loki'
        query: '{$${__tags}} | trace_id = "$${__trace.traceId}"'
        tags:
          - key: 'service.name'
            value: 'service_name'
        
      serviceMap:
        datasourceUid: 'prometheus'
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: 'loki'

  # - name: Alertmanager
  #   uid: alertmanager
  #   type: alertmanager
  #   access: proxy
  #   url: http://localhost:9093
  #   jsonData:
  #     implementation: prometheus
  #   orgId: 1
  #   basicAuth: false
  #   isDefault: false
  #   version: 1
  #   editable: true # set to true to be able to change the datasource in the UI
  #   apiVersion: 1
